version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "trades:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  app:
    restart: always
    build: .
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - kafka
      - zookeeper
      - redis